max_epochs: 3
gpus: 1
precision: 16
accumulate_grad_batches: 2

# 로깅 관련 설정
logging:
  log_every_n_steps: 100
  plot_every_n_epochs: 1
  save_dir: "${paths.log_dir}"  # config.yaml의 paths.log_dir 참조
  
  # WandB 설정
  wandb:
    enabled: true
    project: "dialogue-summarization"
    name: "${experiment_name}"

# 체크포인트 설정
checkpoint:
  dirpath: "${paths.log_dir}/checkpoints"
  filename: "model-{epoch:02d}-{val_loss:.2f}"
  save_top_k: 3
  monitor: "val_loss"
  mode: "min"
