name: lang
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - pytorch-lightning
  - transformers
  - numpy
  - pandas
  - matplotlib
  - wandb
  - hydra-core
  - omegaconf
  - scikit-learn
  - tqdm
  - pip
  - pip:
    - datasets
    - evaluate
    - rouge-score
    - sentencepiece
    - accelerate
    - bitsandbytes
    - peft
