name: lang
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=22.0
  - pytorch=2.0.0
  - torchvision
  - transformers
  - datasets
  - evaluate
  - nltk
  - pandas
  - numpy
  - scikit-learn
  - wandb
  - hydra-core
  - tqdm
  - pip
  - pip:
    - bitsandbytes
    - accelerate
    - peft
    - pytorch-lightning
    - sentencepiece
    - protobuf
    - rouge-score
    - bert-score
    - sacrebleu
    - torchmetrics<1.0.0
