name: dialogue-summarization
channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=22.0
  - cudatoolkit=11.8
  - pytorch>=2.0.0
  - torchvision
  - pytorch-cuda=11.8
  - transformers>=4.30.0
  - datasets>=2.12.0
  - evaluate>=0.4.0
  - nltk>=3.8
  - pandas>=1.5.0
  - numpy>=1.24.0
  - scikit-learn>=1.2.0
  - wandb>=0.15.0
  - hydra-core>=1.3.0
  - omegaconf>=2.3.0
  - tqdm>=4.65.0
  - pip:
    - bitsandbytes>=0.41.1
    - accelerate>=0.21.0
    - peft>=0.4.0
    - pytorch-lightning>=2.0.0
    - sentencepiece>=0.1.99
    - protobuf>=3.20.0
    - rouge-score>=0.1.2
    - bert-score>=0.3.13
    - sacrebleu>=2.3.1 
    - torchmetrics
    - hydra-core
