name: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
tokenizer_name: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

max_length: 512
num_beams: 4
learning_rate: 3e-5
weight_decay: 0.01
use_fp16: false
use_pretrained: true
use_custom: false
